# Generated by Django 3.1.7 on 2021-03-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('try', '0002_auto_20210310_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
