# Generated by Django 3.1.7 on 2021-03-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('try', '0003_auto_20210310_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
